//package com.myolq.myexam.greendao.db;
//
//import java.util.Map;
//
//import org.greenrobot.greendao.AbstractDao;
//import org.greenrobot.greendao.AbstractDaoSession;
//import org.greenrobot.greendao.database.Database;
//import org.greenrobot.greendao.identityscope.IdentityScopeType;
//import org.greenrobot.greendao.internal.DaoConfig;
//
//import com.myolq.myexam.greendao.bean.SingleBean;
//
//import com.myolq.myexam.greendao.db.SingleBeanDao;
//
//// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
//
///**
// * {@inheritDoc}
// *
// * @see org.greenrobot.greendao.AbstractDaoSession
// */
//public class DaoSession extends AbstractDaoSession {
//
//    private final DaoConfig singleBeanDaoConfig;
//
//    private final SingleBeanDao singleBeanDao;
//
//    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
//            daoConfigMap) {
//        super(db);
//
//        singleBeanDaoConfig = daoConfigMap.get(SingleBeanDao.class).clone();
//        singleBeanDaoConfig.initIdentityScope(type);
//
//        singleBeanDao = new SingleBeanDao(singleBeanDaoConfig, this);
//
//        registerDao(SingleBean.class, singleBeanDao);
//    }
//
//    public void clear() {
//        singleBeanDaoConfig.clearIdentityScope();
//    }
//
//    public SingleBeanDao getSingleBeanDao() {
//        return singleBeanDao;
//    }
//
//}
